version: '3'
services:

  travelperk-php-api-types:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: travelperk-php-api-types
    entrypoint: "vendor/bin/phpunit"
    tty: false
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - vendor:/usr/src/app/vendor

volumes:
  vendor:
